.TH "MASONRY CREATE NOTEBOOK" "1" "2022-12-11" "0.0.2" "masonry create notebook Manual"
.SH NAME
masonry\-create\-notebook \- 
.SH SYNOPSIS
.B masonry create notebook
[OPTIONS]
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the DataBricks orchistrator notebook being created
.TP
\fB\-\-dir\fP TEXT
Location to create the new Databricks orchistrator notebook being created
