.TH "MASONRY CREATE LIBRARY" "1" "2022-12-11" "0.0.2" "masonry create library Manual"
.SH NAME
masonry\-create\-library \- 
.SH SYNOPSIS
.B masonry create library
[OPTIONS]
.SH OPTIONS
.TP
\fB\-\-name\fP TEXT
Name of the python library being created
.TP
\fB\-\-desc\fP TEXT
Simple description of the python library being created
.TP
\fB\-\-author\fP TEXT
Name of the python library creator
.TP
\fB\-\-dir\fP TEXT
Location to create the new Databricks notebook being created
