.TH "MASONRY" "1" "2022-12-11" "0.0.2" "masonry Manual"
.SH NAME
masonry \- 
.SH SYNOPSIS
.B masonry
[OPTIONS] COMMAND [ARGS]...
.SH COMMANDS
.PP
\fBcreate\fP
  .PP
  See \fBmasonry-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBbuild\fP
  .PP
  See \fBmasonry-build(1)\fP for full documentation on the \fBbuild\fP command.
.PP
\fBtest\fP
  .PP
  See \fBmasonry-test(1)\fP for full documentation on the \fBtest\fP command.
