.TH "MASONRY CREATE" "1" "2022-12-11" "0.0.2" "masonry create Manual"
.SH NAME
masonry\-create \- 
.SH SYNOPSIS
.B masonry create
[OPTIONS] COMMAND [ARGS]...
.SH COMMANDS
.PP
\fBlibrary\fP
  .PP
  See \fBmasonry create-library(1)\fP for full documentation on the \fBlibrary\fP command.
.PP
\fBnotebook\fP
  .PP
  See \fBmasonry create-notebook(1)\fP for full documentation on the \fBnotebook\fP command.
