---
trigger:
  - main

jobs:
  - job: CodeBase_Linting
    displayName: Codebase Linting Checks
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
          docker pull github/super-linter:v4.8.7
          chmod 755 ./Masonry/scripts/Lint.sh
          ./Masonry/scripts/Lint.sh $(System.DefaultWorkingDirectory)
      displayName: 'Codebase linting checks with Super-Linter'
