---
name: masonry-10.4LTS
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - databricks-connect==10.4.*
      - six
      - nutter
      - pytest
      - pylint
      - pre-commit
      - black
      - mypy
      - autopep8
      - flake8
      - bandit
      - isort
      - pydocstyle
      - mock
      - types-mock
      - Pandas
      - pyarrow
      - cookiecutter
variables:
  DATABRICKS_ADDRESS: https
  DATABRICKS_API_TOKEN: dapi*
  DATABRICKS_CLUSTER_ID: 1108-***
  DATABRICKS_ORG_ID: 6872*
  DATABRICKS_PORT: 8787
